general {
    colors = true
    interval = 5
}

order += "mpd_status"
order += "volume_status"
order += "weather_owm"
order += "backlight"
order += "diskdata"
order += "ethernet enp0s31f6"
order += "wifi"
#order += "net_rate"
order += "online_status"
order += "battery_level"
order += "time"

mpd_status{
    state_pause = ""
    state_play = ""
    state_stop = ""
    format = "{state} [[[{artist} - ]{title}]|[{file}]]"
    on_click 1 = "exec mpc toggle; exec py3-cmd refresh all"
    on_click 2 = "refresh"
    on_click 3 = "exec mpc next; exec py3-cmd refresh all"
}

volume_status {
    color = "#4169e1"
    format = " {percentage}%"
    format_muted = ""
    on_click 1 = "exec pactl set-sink-volume 0 +5% ; exec py3-cmd refresh all"
    on_click 3 = "exec pactl set-sink-volume 0 -5% ; exec py3-cmd refresh all"
}

weather_owm {
    color = "#17C3EB"
    api_key = ""
    unit_temperature = "c"
    format = "{city} {temperature}[ {rain}] {description}"
}

backlight {
    color = "#ffd700"
    format = "{level}"
}

diskdata {
    color = "#00FFFF"
    disk = "sda6"
    format = "{used_percent}%"
}

ethernet enp0s31f6 {
    format_up = "%speed %ip"
    format_down = ""
}
wifi {

    format = "{ssid}  {signal_percent} {ip}|"
}

net_rate {
    format = "{interface} {up} {down}"
    unit = "MiB/s"
}

online_status{
    icon_off = ""
    icon_on = ""
}

battery_level {
    format = "{icon} {percent}% {time_remaining}"
    charging_character = ""
    blocks = ""
}
