[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#00000000"
idle_fg = "#ffffffff"
separator = ""
separator_bg = "#00000000"
separator_fg = "#00000000"
good_bg = "#00000000"
good_fg = "#00FF00"
warning_bg = "#00000000"
warning_fg = "#fce100"
critical_bg = "#00000000"
critical_fg = "#ff0000"
info_bg = "#00000000"
info_fg = "#00ffff"

[icons]
icons = "awesome4"

[[block]]
block = "music"
player = "mpd"
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $play |} "

[[block]]
block = "weather"
format = " $icon $weather $temp, $wind m/s $direction"
# API key and City ID are written in env var
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "wlan0"
format = " $icon ^icon_net_down $speed_down.eng(prefix:K,w:4) ^icon_net_up $speed_up.eng(prefix:K,w:4) "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M) ($mem_total_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
format = "$percentage $time"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%Y-%m-%d %a %H:%M:%S')"
