$font = sans-serif

general {
    hide_cursor = false
    fractional_scaling = 1
}

uncomment to enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 4, linear
    animation = fadeOut, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = 0, 20%
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 30%
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 15%, 3.5%
    outline_thickness = 0
    inner_color = rgba(ffffff55) # just a blurry box
    check_color = rgba(00ff99ee)
    fail_color = rgba(ff6633ee)

    font_color = rgb(ffffff)
    fade_on_empty = false
    rounding = 50

    font_family = $font
    placeholder_text = Input password or scan fingerprint
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -25%
    halign = center
    valign = center
}
