#!/bin/bash

CURRENT=$(mpc current)
TITLE=$(mpc -f '%title%' current)
ARTIST=$(mpc -f '%artist%' current)

if [[${#TITLE} -eq 0 ]] || [[ ${#ARTIST} -eq 0 ]]; then
    MSG=$CURRENT
elif [[ ${#CURRENT} -ge 50 ]]; then
    MSG=$TITLE
else
    MSG=$CURRENT
fi

echo $MSG
