# Required files
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"

# Optional
music_directory    "/mnt/Data/Music/MusicSync"
playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

#Network settings
bind_to_address "any"
port "6600"

# Playlist support
playlist_plugin {
    name "cue"
    enabled "true"
}

# Resampler
resampler {
    plugin "soxr"
    quality "very high"
}

# Output info
audio_output {
    type "jack"
    name "JACK output on SYA-TP"
}

audio_output {
    type "alsa"
    name "ALSA output on SYA-TP"
    device "hw:0"
}
audio_output {
    type "pulse"
    name "PulseAudio output on SYA-TP"
}

audio_output {
    type                    "fifo"
    name                    "FIFO local output for cli-visualizer"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
