#!/bin/bash
set -eu

MAILDIR="$HOME/.mail"

# safe_move: move $1 to $2, remove its uid part
function safe_move {
    s=${1##*/}; s=${s%%,*}
    #echo "Moving: $1 -> $2/$s";
    mv -f $1 $2/$s;
}

# tag_move: move mails in folder $1 with custom search string $2 to folder $3
function tag_move {
    filter_str="path:$1/** AND $2 AND NOT folder:$3"
    #echo "$filter_str"
    count="$(notmuch count --output=files --exclude=false "$filter_str")"
    echo "Moving $count messages in $1 with $2 to $3"
    for i in $(notmuch search --exclude=false --output=files "$filter_str"); do
        safe_move "$i" "$MAILDIR/$3/cur"
    done
}

# tag_delete: delete mail in folder $1 with custom search string $2
function tag_delete {
    filter_str="folder:$1 AND $2"
    count="$(notmuch count --output=files --exclude=false "$filter_str")"
    echo "Deleting $count messages in $1 with $2"
    for i in $(notmuch search --exclude=false --output=files "$filter_str"); do
        rm "$i"
        #echo "Removing $i"
    done
}

# === Magic Starts Here ===
echo "[PRE-NEW] pre-new hook start. Maildir is $MAILDIR"
notmuch new --no-hooks

# -delete
TAG="tag:deleted"
echo "[PRE-NEW] processing $TAG"
tag_move "gmail" "$TAG" "gmail/[Gmail]/Trash"
tag_move "lecs" "$TAG" "lecs/Trash"
tag_move "csc" "$TAG" "csc/Trash"

# -junk
TAG="tag:junk"
echo "[PRE-NEW] processing $TAG"
tag_move "gmail" "$TAG" "gmail/[Gmail]/Spam"
tag_move "lecs" "$TAG" "lecs/Spam"
tag_move "csc" "$TAG" "csc/Spam"

# -archive
TAG="NOT tag:inbox"
echo "[PRE-NEW] processing $TAG"
tag_delete "gmail/Inbox" "$TAG"
tag_move "lecs/Inbox" "$TAG" "lecs/Archive"

echo "[PRE-NEW] running mbsync"
mbsync -a -c ~/.config/isync/mbsyncrc

echo "[PRE-NEW] pre-new hook complete"
